# travis-ci.org build & test configuration
sudo: required

language: python

services:
  - docker

before_install:
  - docker pull hepsw/cvmfs-cms
  - sudo mkdir /software && sudo chown $USER /software

install:
 - source bin/env.sh

script:
  - python python/ntp/utils/test/test_utils.py
  - ./test/test.sh
  - sudo docker build -t kreczko/ntp .
  - sudo docker run -t --privileged=true kreczko/ntp
cache: apt
